
- hosts: localhost 
  connection: local
  gather_facts: False
  vars:
    prefix: newvm
    count: 1
    padding: 3
    vmware_template: RHEL_7

  tasks:
    - name: create the instance
      vmware_guest:
        validate_certs: no
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        name: "{{ prefix }}"
        exact_count: "{{ count }}"
        exact_count_padding: "{{ padding }}"
        wait_for_ip_address: yes
        template: "{{ vmware_template }}"
        folder: "{{ folder }}"
        datacenter: "{{ datacenter }}"
      
        disk:
            - size_gb: 10
              type: thin
              datastore: "{{ datastore }}"
    
